services:

  redis:
    image: redis:8
    container_name: redis-lab
    ports:
      - "6379:6379"
    restart: always

  redis-geo-api:
    build:
      context: ./Redis.Geo
      dockerfile: Dockerfile
    container_name: redis-geo-api
    ports:
      - "5000:8080"
    depends_on:
      - redis
    environment:
      - Redis__ConnectionString=redis:6379